import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
// import { motion } from 'framer-motion'
// import AOS from 'aos';
// import 'aos/dist/aos.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>mbifenzi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"/>
      </Head>
    </div>
  )
}
